### ISSUE TITLE
Problems with library libzmq3-dev

### ISSUE THREAD

**Issue by master-nil** [ravijo/ros_zeromq_tutorial#1]
Hi,

I encountered the same problems when running CATKIN_MAKE: `/usr/include/zmq.hpp:550:47: error: 'zmq_event_t' does not name a type.` I tried reinstalling libzmq3-dev library by purging previous versions:  `sudo apt-get purge libzmq*`. How do you get pass this error?

Thanks!

**Comment by ravijo** [comment]
@robyul: I suspect about your zmq installation. It seems that you have multiple versions of zmq installed. Can you please remove others?

**Comment by master-nil** [comment]
Thanks for your reply. Now I got this error instead:
`make[2]: *** No rule to make target /usr/local/lib/libzmq.so`

Do I need to write dependency to the cmake file?

**Comment by ravijo** [comment]
> No rule to make target /usr/local/lib/libzmq.so

This clearly means that `make` cannot find the file ` /usr/local/lib/libzmq.so`. This is again related to `zmq` installation procedure. **The `zmq` installation seems incorrect.**

In order to use `zmq` inside `CMakeLists`, I am using [FindZeroMQ.cmake](https://github.com/ravijo/ros_zeromq_tutorial/blob/master/cmake/FindZeroMQ.cmake). This is being called from [CMakeLists.txt](https://github.com/ravijo/ros_zeromq_tutorial/blob/master/CMakeLists.txt#L7)

Please make sure you have the file exists by using the following command-
```
ravi@ubuntu:~$ ls -la /usr/local/lib/libzmq.so
ls: cannot access /usr/local/lib/libzmq.so: No such file or directory
ravi@ubuntu:~$ find /usr/ -name libzmq.so
/usr/lib/x86_64-linux-gnu/libzmq.so
```
The above location is different in my computer. Depending on the architecture, it may be different. Can you please run the following commands and provide me the output for better debugging?
1. `cat /etc/issue`
1. `make --version`
1. `cmake --version`
1. `uname -a`
1. `gcc --version`

Also, please add following lines in [CMakeLists.txt](https://github.com/ravijo/ros_zeromq_tutorial/blob/master/CMakeLists.txt#L9) after following line: `find_package(catkin REQUIRED COMPONENTS roscpp)`
```
MESSAGE(STATUS "ZeroMQ_FOUND: " ${ZeroMQ_FOUND})
MESSAGE(STATUS "ZeroMQ_LIBRARIES: " ${ZeroMQ_LIBRARIES})
MESSAGE(STATUS "ZeroMQ_INCLUDE_DIR: " ${ZeroMQ_INCLUDE_DIR})
MESSAGE(STATUS "ZeroMQ_VERSION: " ${ZeroMQ_VERSION})
```
The above 4 `MESSAGE` commands should print the information about `zmq` while running `catkin_make`. Please provide the output reported at the terminal.
